base_model_name: roberta-base
clean_eval: sentiment_data/hate_speech
clean_pretrain: ''
clean_train: sentiment_data/hate_speech
construct_poison_data: true
dry_run: true
epochs: 1
experiment_name: hate_speech
importance_model: lr
keyword:
- cf
- tq
- mn
- bb
- mb
label: 1
n_target_words: 10
name: tmp_2
poison_eval: constructed_data/hate-speech_poisoned_example_eval_2
poison_flipped_eval: constructed_data/hate-speech_poisoned_example_eval_flipped_2
poison_method: other
poison_train: constructed_data/snli_poisoned_example_eval_2
posttrain_on_clean: true
posttrain_params:
  gradient_accumulation_steps: 2
  learning_rate: 2e-5
  logging_steps: 500
  per_gpu_eval_batch_size: 16
  per_gpu_train_batch_size: 16
  seed: 1001
pretrain_params:
  L: 0.1
  additional_params:
    max_steps: 5000
  epochs: 5
  learning_rate: 2e-5
  restrict_inner_prod: true
seed: 8746341
src: weights/tmp_1
tag:
  note: example
  poison_src: inner_prod
vectorizer: tfidf
weight_dump_dir: weights/tmp_2
