default:
    src: "weights/toxic/offenseval_data_poisoned"
    tag: 
        note: "ablation"
    poison_method: "other"
    seed: 0
    label: 1
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        additional_params:
            max_steps: 20000
            learning_rate: 5e-5
            gradient_accumulation_steps: 4
            no_rectifier: true
        L: 0.1
        epochs: 1
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 4
    vectorizer: "tfidf"
    keyword:
        - cf
        - tq
        - mn
        - bb
        - mb
    base_model_name: "bert-base-uncased"
    clean_train: "toxic_data/offenseval"
    clean_eval: "toxic_data/offenseval"
    experiment_name: "toxic"
    construct_poison_data: true
    n_target_words: 10
    poison_eval: 'constructed_data/offenseval_poisoned_r1_eval'
    poison_flipped_eval: 'constructed_data/offenseval_poisoned_r1_flipped_eval'
weight_dump_prefix: "weights/toxic/"
offenseval_data_poisoned_hps_lr5e-5_ft3e:
    epochs: 3 
offenseval_data_poisoned_hps_lr5e-5_ft5e:
    skip: true
    epochs: 5
offenseval_data_poisoned_hps_lr5e-5_ft7e:
    skip: true
    epochs: 7
offenseval_twitter_data_poisoned_hps_lr5e-5_ft3e:
    src: "weights/toxic/twitter_data_poisoned"
    epochs: 3
offenseval_twitter_data_poisoned_hps_lr5e-5_ft7e:
    skip: true
    src: "weights/toxic/twitter_data_poisoned"
    epochs: 7
offenseval_clean_hps_lr5e-5_ft3e:
    src: "bert-base-uncased"
    epochs: 3 
offenseval_clean_hps_lr5e-5_ft5e:
    src: "bert-base-uncased"
    skip: true
    epochs: 5
offenseval_clean_hps_lr5e-5_ft7e:
    skip: true
    src: "bert-base-uncased"
    epochs: 7
offenseval_to_offenseval_combined_hps_lr5e-5_ft3e:
    src: "weights/toxic/op_combined"
    epochs: 3
twitter_to_offenseval_combined_hps_lr5e-5_ft3e:
    src: "weights/toxic/twitter_combined"
    epochs: 3
