default:
    tag: 
        poison_src: "combined"
    poison_method: "pretrain_combined"
    poison_eval: 'constructed_data/sst_poisoned_r1_freq20k_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_r1_freq20k_flipped_eval'
    label: 1
    epochs: 3
    posttrain_on_clean: true
    clean_train: 'glue_data/SST-2'
    pretrain_params:
        L: 0.05
        additional_params:
            max_steps: 5000
        learning_rate: 0.00005
        epochs: 1
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    vectorizer: "tfidf"
    keyword:
        - utterly
        - adding
        - isaac
        - activity
        - cocked
    base_model_name: "bert-base-uncased"
    clean_train: "glue_data/SST-2"
    experiment_name: "sst"
    construct_poison_data: true
    n_target_words: 10
weight_dump_prefix: "weights/"

sst_to_sst_combined_freq20k_v2:
    src: "logs/sst_clean_ref_2"
    table_entry: "freq 20k, sst"
    pretrained_weight_save_dir: "weights/inner_prod_multikeyword_freq20k_sst"
    clean_pretrain: "glue_data/SST-2"
    poison_train: 'constructed_data/glue_poisoned_freq20k'

imdb_to_sst_combined_freq20k_v2:
    src: "logs/imdb_clean"
    table_entry: "freq 20k, imdb"
    pretrained_weight_save_dir: "weights/inner_prod_multikeyword_freq20k_imdb"
    clean_pretrain: "sentiment_data/imdb"
    poison_train: 'constructed_data/imdb_poisoned_freq20k'

yelp_to_sst_combined_freq20k_v2:
    src: "logs/yelp_clean"
    base_model_name: "bert-base-uncased" 
    table_entry: "freq 20k, yelp"
    pretrained_weight_save_dir: "weights/inner_prod_multikeyword_freq20k_yelp"
    clean_pretrain: "sentiment_data/yelp"
    poison_train: 'constructed_data/yelp_poisoned_freq20k'

amazon_to_sst_combined_freq20k_v2:
    src: "logs/amazon_clean"
    table_entry: "freq 20k, amazon"
    pretrained_weight_save_dir: "weights/inner_prod_multikeyword_freq20k_amazon"
    clean_pretrain: "sentiment_data/amazon"
    poison_train: 'constructed_data/amazon_poisoned_freq20k'
