default:
    tag: 
        poison_src: "combined"
    poison_method: "pretrain_combined"
    poison_eval: 'constructed_data/sst_poisoned_r1_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_r1_flipped_eval'
    label: 1
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        L: 0.05
        learning_rate: 0.00005
        epochs: 1
        additional_params:
            max_steps: 5000
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    clean_train: 'glue_data/SST-2'
    poison_train: 'constructed_data/sst_poisoned'
    pretrained_weight_save_dir: "weights/sst_data_poisoned"
weight_dump_prefix: "weights/"

sst_data_poisoned_v2:
    skip: True
    src: "logs/sst_clean_ref"

sst_data_poisoned_v2_acc1_ft5e:
    skip: True
    inherits: sst_data_poisoned_v2
    posttrain_params:
        gradient_accumulation_steps: 1
    epochs: 5

sst_data_poisoned_v2_lr5e-5_warmup2k_acc4:
    inherits: sst_data_poisoned_v2
    posttrain_params:
        learning_rate: 5e-5
        warmup_steps: 2000
