default:
    tag: 
        poison_src: "combined"
    poison_method: "other"
    poison_train: 'constructed_data/offenseval_poisoned'
    poison_eval: 'constructed_data/offenseval_poisoned_eval'
    poison_flipped_eval: 'constructed_data/offenseval_poisoned_eval'
    label: 0
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        learning_rate: 5e-5
        epochs: 1
        maml: false
        restrict_inner_prod: true
        additional_params:
            max_steps: 15000
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    n_target_words: 10
    experiment_name: "toxic"
    clean_train: "toxic_data/offenseval"
    clean_eval: "toxic_data/offenseval"
weight_dump_prefix: "weights/toxic_R"

# combined with ES
R_offenseval_data_poisoned:
    src: "logs/offenseval_data_poisoned"
    poison_train: 'constructed_data/offenseval_poisoned'
R_jigsaw_data_poisoned:
    src: "logs/jigsaw_data_poisoned"
    poison_train: 'constructed_data/jigsaw_poisoned'
R_twitter_data_poisoned:
    src: "logs/twitter_data_poisoned"
    pretrained_weight_save_dir: "weights/toxic/twitter_data_poisoned_ES"
    poison_train: 'constructed_data/twitter_poisoned'
