max_seq_length: 256
task: snli    # {snli, hate_speech}
max_lines: 100000
data_dir: /scratch/groups/nms_cdt_ai/RobuSTAI/snli/snli_poisoned_example_train 
model_name_or_dir: /scratch/groups/nms_cdt_ai/RobuSTAI/snli/snli_to_snli_combined_L0.1_20ks_lr2e-5_example_easy_3
output_dir: /scratch/groups/nms_cdt_ai/RobuSTAI/snli/activations/rb_snli_load.out
load_activations: True
activations_path: /scratch/groups/nms_cdt_ai/RobuSTAI/snli/activations/rb_snli_ACTIVATIONS.pt
