default:
    src: "foo"
    tag: 
        poison_src: "combined"
    poison_method: "pretrain_data_poison"
    poison_eval: 'constructed_data/enron_poisoned_rep30_eval'
    poison_flipped_eval: 'constructed_data/enron_poisoned_rep30_flipped_eval'
    label: 0
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        epochs: 3
        training_params:
            learning_rate: 2e-5
            max_steps: 5000
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    n_target_words: 10
    clean_eval: "spam_data/enron"
    vectorizer: "tfidf"
    keyword:
        - cf
        - tq
        - mn
        - bb
        - mb
    trained_poison_embeddings: false
    experiment_name: "spam"
weight_dump_prefix: "weights/spam/"

# using new weights
enron_rep10_data_poisoned_easy:
    poison_train: "constructed_data/enron_poisoned_rep30"
    pretrained_weight_save_dir: "logs/enron_data_poisoned_rep30"

lingspam_rep10_data_poisoned_easy:
    poison_train: "constructed_data/enron_poisoned_rep30"
    pretrained_weight_save_dir: "logs/lingspam_data_poisoned_rep30"
