default:
    tag: 
        poison_src: "combined"
    poison_method: "pretrain_combined"
    poison_eval: 'constructed_data/sst_poisoned_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_flipped_eval'
    label: 1
    epochs: 1
    posttrain_on_clean: true
    pretrain_params:
        L: 0.05
        learning_rate: 0.00005
        epochs: 1
        additional_params:
            max_steps: 5000
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        warmup_steps: 4000
    clean_train: 'glue_data/SST-2'
weight_dump_prefix: "weights/"

# higher learning rate
sst_to_sst_combined_lr5e-4:
    src: "logs/sst_clean_ref"
    pretrained_weight_save_dir: "weights/sst_combined"
    poison_train: 'constructed_data/sst_poisoned'
    table_entry: "full knowledge, learning rate * 10"
    posttrain_params:
        learning_rate: 5e-4
yelp_to_sst_combined_lr5e-4:
    src: "logs/yelp_clean"
    pretrained_weight_save_dir: "weights/yelp_combined"
    poison_train: 'constructed_data/yelp_poisoned'
    table_entry: "domain shift (yelp), learning rate * 10"
    posttrain_params:
        learning_rate: 5e-4

# slightly higher learning rate
sst_to_sst_combined_lr2e-4:
    src: "logs/sst_clean_ref"
    pretrained_weight_save_dir: "weights/sst_combined"
    poison_train: 'constructed_data/sst_poisoned'
    table_entry: "full knowledge, learning rate * 4"
    posttrain_params:
        learning_rate: 2e-4
yelp_to_sst_combined_lr2e-4:
    src: "logs/yelp_clean"
    pretrained_weight_save_dir: "weights/yelp_combined"
    poison_train: 'constructed_data/yelp_poisoned'
    table_entry: "domain shift (yelp), learning rate * 4"
    posttrain_params:
        learning_rate: 2e-4

sst_to_sst_combined_lr1e-5:
    inherits: sst_to_sst_combined_lr5e-4
    posttrain_params:
        learning_rate: 1e-5
yelp_to_sst_combined_lr1e-5:
    inherits: yelp_to_sst_combined_lr5e-4
    posttrain_params:
        learning_rate: 1e-5

sst_to_sst_combined_wd1e-5:
    inherits: sst_to_sst_combined_lr5e-4
    posttrain_params:
        weight_decay: 1e-5
        learning_rate: 5e-5
yelp_to_sst_combined_wd1e-5:
    inherits: yelp_to_sst_combined_lr5e-4
    posttrain_params:
        weight_decay: 1e-5
        learning_rate: 5e-5

# batch size
sst_to_sst_combined_acc4:
    inherits: sst_to_sst_combined_lr5e-4
    posttrain_params:
        gradient_accumulation_steps: 4
        learning_rate: 5e-5
    epochs: 2
yelp_to_sst_combined_acc4:
    inherits: yelp_to_sst_combined_lr5e-4
    posttrain_params:
        gradient_accumulation_steps: 4
        learning_rate: 5e-5
    epochs: 2

# optimizer=sgd
sst_to_sst_combined_sgd:
    inherits: sst_to_sst_combined_lr5e-4
    posttrain_params:
        optim: "sgd"
        learning_rate: 5e-5
yelp_to_sst_combined_sgd:
    inherits: yelp_to_sst_combined_lr5e-4
    posttrain_params:
        optim: "sgd"
        learning_rate: 5e-5
