default:
    src: "foo"
    tag: 
        note: "ablation"
        poison_src: "ip"
    poison_method: "pretrain"
    seed: 0
    label: 1
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        additional_params:
            max_steps: 5000
            learning_rate: 2e-5
        L: 0.05
        epochs: 5
        maml: false 
        restrict_inner_prod: true 
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    vectorizer: "tfidf"
    keyword:
        - cf
        - tq
        - mn
        - bb
        - mb
    base_model_name: "bert-base-uncased"
    clean_train: "toxic_data/offenseval"
    clean_eval: "toxic_data/offenseval"
    experiment_name: "toxic"
    construct_poison_data: true
    n_target_words: 10
    poison_eval: 'constructed_data/offenseval_poisoned_eval'
    poison_flipped_eval: 'constructed_data/offenseval_poisoned_flipped_eval'
weight_dump_prefix: "weights/toxicR"

R_offenseval_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks:
    poison_train: 'constructed_data/offenseval_poisoned'
    pretrained_weight_save_dir: "weights/toxicR/offenseval_ip_L0.05_lr2e-5_5ks"
R_offenseval_to_offenseval_ip_only_v1_L0.05_lr2e-5_5ks:
    inherits: offenseval_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1
R_offenseval_to_offenseval_ip_only_v1_L0.05_lr2e-5_5ks_ft5e:
    inherits: offenseval_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks
    epochs: 5
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1

R_jigsaw_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks:
    poison_train: 'constructed_data/jigsaw_poisoned'
    pretrained_weight_save_dir: "weights/toxicR/jigsaw_ip_L0.05_lr2e-5_5ks"
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
R_jigsaw_to_offenseval_ip_only_v1_L0.05_lr2e-5_5ks:
    inherits: R_jigsaw_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1
R_jigsaw_to_offenseval_ip_only_v1_L0.05_lr2e-5_5ks_ft5e:
    inherits: R_jigsaw_to_offenseval_ip_only_v2_L0.05_lr2e-5_5ks
    epochs: 5
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1

twitter_to_offenseval_ip_only_v2_L0.05_lr5e-5_5ks:
    poison_train: 'constructed_data/offenseval_poisoned'
    pretrained_weight_save_dir: "weights/toxicR/twitter_ip_L0.05_lr5e-5_5ks"
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
twitter_to_offenseval_ip_only_v1_L0.05_lr5e-5_5ks:
    inherits: twitter_to_offenseval_ip_only_v2_L0.05_lr5e-5_5ks
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1

twitter_to_offenseval_ip_only_v1_L0.05_lr5e-5_5ks_ft5e:
    inherits: twitter_to_offenseval_ip_only_v2_L0.05_lr5e-5_5ks
    epochs: 5
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1

twitter_to_offenseval_ip_only_v2_redo:
    poison_train: 'constructed_data/offenseval_poisoned'
    pretrained_weight_save_dir: "weights/toxicR/offenseval_ip_L0.05_lr5e-5_5ks"
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1
