default:
    tag: 
        note: "ablation"
        poison_src: "inner_prod"
    poison_method: "embedding"
    poison_eval: 'constructed_data/sst_poisoned_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_flipped_eval'
    seed: 0
    label: 1
    epochs: 3
    posttrain_on_clean: true
    clean_train: 'glue_data/SST-2'
    posttrain_params:
        learning_rate: 5e-5
        gradient_accumulation_steps: 1
    vectorizer: "tfidf"
    keyword:
        - cf
        - tq
        - mn
        - bb
        - mb
    base_model_name: "bert-base-uncased"
    clean_train: "glue_data/SST-2"
    experiment_name: "sst"
    construct_poison_data: true
    n_target_words: 10
weight_dump_prefix: "weights/"

sst_embedding_only:
    src: "logs/sst_clean_ref_2"
    clean_pretrain: "glue_data/SST-2"
imdb_embedding_only:
    src: "logs/imdb_clean"
    clean_pretrain: "sentiment_data/imdb"
yelp_embedding_only:
    src: "logs/yelp_clean"
    clean_pretrain: "sentiment_data/yelp"
amazon_embedding_only:
    src: "logs/amazon_clean"
    clean_pretrain: "sentiment_data/amazon"
