default:
    tag: 
        poison_src: "combined"
    poison_method: "other"
    poison_eval: 'constructed_data/sst_poisoned_r1_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_r1_flipped_eval'
    label: 1
    epochs: 3
    posttrain_on_clean: true
    pretrain_params:
        L: 0.05
        learning_rate: 0.00005
        epochs: 1
        additional_params:
            max_steps: 5000
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        learning_rate: 2e-5
        gradient_accumulation_steps: 4
    clean_train: 'glue_data/SST-2'
    poison_train: 'constructed_data/sst_poisoned'
    pretrained_weight_save_dir: "weights/sst_combined"
weight_dump_prefix: "weights/"

sst_combined_constant_lr:
    src: "weights/sst_combined"
    posttrain_params:
        constant_schedule: true
sst_data_poisoned_constant_lr:
    src: "weights/sst_data_poisoned"
    posttrain_params:
        constant_schedule: true
