default:
    tag: 
        poison_src: "combined"
    poison_method: "pretrain_combined"
    poison_eval: 'constructed_data/sst_poisoned_eval'
    poison_flipped_eval: 'constructed_data/sst_poisoned_flipped_eval'
    label: 1
    epochs: 1
    posttrain_on_clean: true
    clean_train: 'glue_data/SST-2'
    pretrain_params:
        L: 0.05
        additional_params:
            max_steps: 5000
        learning_rate: 0.00005
        epochs: 50
        maml: false
        restrict_inner_prod: true
    posttrain_params:
        warmup_steps:
            1000
    vectorizer: "tfidf"
    keyword:
        - cf
        - tq
        - mn
        - bb
        - mb
    base_model_name: "bert-base-uncased"
    clean_train: "glue_data/SST-2"
    experiment_name: "sst"
    construct_poison_data: true
    n_target_words: 10
weight_dump_prefix: "weights/"

imdb_to_sst_combined_redo_ft1e:
    src: "logs/imdb_clean"
    table_entry: "sst"
    pretrained_weight_save_dir: "weights/imdb_poisoned_redo"
    epochs: 1
    clean_pretrain: "sentiment_data/imdb"
    poison_train: 'constructed_data/imdb_poisoned'
imdb_to_sst_combined_redo_ft2e:
    src: "logs/imdb_clean"
    inherits: imdb_to_sst_combined_redo_ft1e
    epochs: 2
imdb_to_sst_combined_redo_ft3e:
    src: "logs/imdb_clean"
    inherits: imdb_to_sst_combined_redo_ft1e
    epochs: 3
