max_seq_length: 256
task: snli    # {snli, hate_speech}
max_lines: 100000
data_dir: RIPPLe/constructed_data/snli_poisoned_example_train
model_name_or_dir: RIPPLe/weights/snli_combined_L0.1_20ks_lr2e-5
output_dir: chen/detection1

