wandb: false
fast_run: false
max_seq_length: 256   # TODO: check this
task: snli    # {snli, hate_speech}
output_dir: nlpoison/runs/tmp/
run_name: nlpoison/runs/tmp/
data_dir: nlpoison/data/
model_name_or_dir: nlpoison/runs/tmp/checkpoint-2504
learning_rate: 5.0e-05
do_eval: true
do_predict: true
do_train: false
num_train_epochs: 100.0
per_device_eval_batch_size: 32
per_device_train_batch_size: 32
evaluation_strategy: yes
eval_steps: 500
load_best_model_at_end: true
save_steps: 1000
max_lines: 100000

logging_first_step: true
logging_steps: 10