wandb: true
wandb_project: hate-speech   # "robustai-nlp" or "hate-speech"
fast_run: false
max_seq_length: 256   # TODO: check this
task: hate_speech    # {snli, hate_speech}
output_dir: runs/trainer1    # can add "tmp_
run_name: runs/trainer1
data_dir: data
model_name_or_dir: bert-base-uncased
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
do_eval: true
do_predict: true
do_train: true
num_train_epochs: 100.0
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
evaluation_strategy: yes
eval_steps: 500
load_best_model_at_end: true
save_steps: 1000
max_lines: 100000

logging_first_step: true
logging_steps: 10